### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by moisesrodriguez** [karanpratapsingh/preview-environments#1]
Hey Karan,

I have not test it yet, but awesome job you've done here.  I do have a question that I was not able to figure out while looking at the GitHub action workflow or code, is there a way to insert environment variables to the task definition? My application does need many environment variables to work, just one simple example would be the db credentials.

**Comment by moisesrodriguez** [comment]
Looking a [little more](https://github.com/aws-actions/amazon-ecs-render-task-definition) I can see you can do that in the GitHub action with something like:

```
- name: Render Amazon ECS task definition
   id: render-web-container
   uses: aws-actions/amazon-ecs-render-task-definition@v1
   with:
     task-definition: task-definition.json
     container-name: web
     image: amazon/amazon-ecs-sample-1:latest
     environment-variables: |
        LOG_LEVEL=info
        ENVIRONMENT=prod
```
